spring:
    datasource:
        url: jdbc:mysql://localhost:3307/HOTEL?useUnicode=true$characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: spring.c
    data:
        elasticsearch:
            repositories:
                enabled: true
            cluster-nodes: localhost:9300
            cluster-name: elasticsearch
